export interface DashboardWidget {
  id: string;
  type: 'risk-bar' | 'distribution-chart' | 'employee-table' | 'ai-actions' | 'insights' | 'metrics' | 'individual-risk-analysis' | 'ai-retention-planner' | 'executive-risk-overview' | 'workforce-trends' | 'ai-strategic-insights' | 'enhanced-employee-table' | 'custom';
  title: string;
  data?: any;
  config?: {
    showTitle?: boolean;
    height?: number;
    width?: number;
    minWidth?: number;
    minHeight?: number;
    resizable?: boolean;
    draggable?: boolean;
    [key: string]: any;
  };
  position: {
    x: number;
    y: number;
    w: number;
    h: number;
  };
  aiAction?: {
    type: 'diagnose-risk' | 'create-plan' | 'analyze-trends' | 'generate-report';
    params?: any;
  };
}

export interface DashboardLayout {
  id: string;
  name: string;
  widgets: DashboardWidget[];
  isDefault: boolean;
  createdAt: Date;
  updatedAt: Date;
  templateId?: string;
  autoGenerated?: boolean;
  metadata?: {
    description?: string;
    tags?: string[];
    category?: string;
    author?: string;
    mode?: string;
    roleGenerated?: boolean;
  };
}

export interface DashboardTemplate {
  id: string;
  name: string;
  description: string;
  category: 'executive' | 'hr' | 'manager' | 'analyst' | 'custom';
  widgets: Omit<DashboardWidget, 'id'>[];
  previewImage?: string;
  tags: string[];
  enterpriseOnly: boolean;
  autoGeneration: {
    enabled: boolean;
    triggers: string[];
    rules: AutoGenerationRule[];
  };
}

export interface AutoGenerationRule {
  condition: string;
  action: 'add-widget' | 'remove-widget' | 'modify-widget' | 'rearrange';
  params: any;
}

export interface DashboardConfig {
  gridSize: number;
  maxWidgets: number;
  allowCustomWidgets: boolean;
  enableAutoGeneration: boolean;
  layouts: DashboardLayout[];
  templates: DashboardTemplate[];
  aiIntegration: {
    enabled: boolean;
    quickActions: string[];
    insights: boolean;
  };
}

export interface WidgetData {
  [key: string]: any;
}

export interface DashboardState {
  currentLayoutId: string;
  isEditMode: boolean;
  isCustomizing: boolean;
  selectedWidgets: string[];
  draggedWidget?: DashboardWidget;
  config: DashboardConfig;
}