import React, { useState, useCallback, useMemo } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Layout,
  Save,
  Download,
  Upload,
  Copy,
  Trash2,
  Star,
  StarOff,
  Share2,
  Clock,
  Grid,
  Search
} from 'lucide-react';
import { cn } from '../lib/utils';
import { DashboardLayout } from '../types/dashboard';
import { CustomizationMode } from '../contexts/HomeCustomizationContext';

interface LayoutManagerProps {
  layouts: DashboardLayout[];
  currentLayout: DashboardLayout | null;
  currentMode: CustomizationMode;
  onLayoutSelect: (layoutId: string) => void;
  onLayoutSave: (name: string, description?: string) => Promise<void>;
  onLayoutDelete: (layoutId: string) => Promise<void>;
  onLayoutDuplicate: (layoutId: string, newName: string) => Promise<void>;
  onLayoutExport: (layoutId: string) => void;
  onLayoutImport: (layout: DashboardLayout) => Promise<void>;
  onLayoutSetDefault: (layoutId: string) => Promise<void>;
  onLayoutShare: (layoutId: string) => Promise<string>;
  className?: string;
}

interface LayoutCardProps {
  layout: DashboardLayout;
  isActive: boolean;
  onSelect: () => void;
  onDelete: () => void;
  onDuplicate: () => void;
  onExport: () => void;
  onSetDefault: () => void;
  onShare: () => void;
  canDelete: boolean;
}

const LayoutCard: React.FC<LayoutCardProps> = ({
  layout,
  isActive,
  onSelect,
  onDelete,
  onDuplicate,
  onExport,
  onSetDefault,
  onShare,
  canDelete
}) => {
  const [showActions, setShowActions] = useState(false);
  const [isSharing, setIsSharing] = useState(false);

  const handleShare = useCallback(async () => {
    setIsSharing(true);
    try {
      await onShare();
    } finally {
      setIsSharing(false);
    }
  }, [onShare]);

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className={cn(
        "relative p-4 border rounded-lg transition-all duration-200 cursor-pointer group",
        isActive
          ? "border-blue-500 bg-blue-50 dark:bg-blue-900/20"
          : "border-gray-200 dark:border-gray-700 hover:border-gray-300 dark:hover:border-gray-600 hover:bg-gray-50 dark:hover:bg-gray-800/50"
      )}
      onClick={onSelect}
      onMouseEnter={() => setShowActions(true)}
      onMouseLeave={() => setShowActions(false)}
    >
      {/* Layout Preview */}
      <div className="mb-3">
        <div className="w-full h-16 bg-gray-100 dark:bg-gray-700 rounded border overflow-hidden">
          <div className="p-1 h-full">
            <div className="grid grid-cols-4 gap-1 h-full">
              {layout.widgets.slice(0, 8).map((widget) => (
                <div
                  key={widget.id}
                  className={cn(
                    "bg-white dark:bg-gray-600 rounded-sm",
                    widget.position.w > 6 ? "col-span-2" : "col-span-1",
                    widget.position.h > 3 ? "row-span-2" : "row-span-1"
                  )}
                  style={{
                    gridColumn: `span ${Math.min(widget.position.w / 3, 2)}`,
                    gridRow: `span ${Math.min(widget.position.h / 2, 2)}`
                  }}
                />
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* Layout Info */}
      <div className="mb-2">
        <div className="flex items-center justify-between">
          <h4 className="font-medium text-gray-900 dark:text-gray-100 truncate">
            {layout.name}
          </h4>
          <div className="flex items-center space-x-1">
            {layout.isDefault && (
              <Star className="w-4 h-4 text-yellow-500 fill-current" />
            )}
            {isActive && (
              <div className="w-2 h-2 bg-blue-500 rounded-full" />
            )}
          </div>
        </div>
        
        {layout.metadata?.description && (
          <p className="text-sm text-gray-600 dark:text-gray-400 mt-1 line-clamp-2">
            {layout.metadata.description}
          </p>
        )}
      </div>

      {/* Layout Stats */}
      <div className="flex items-center justify-between text-xs text-gray-500 dark:text-gray-400 mb-3">
        <div className="flex items-center space-x-3">
          <span className="flex items-center space-x-1">
            <Grid className="w-3 h-3" />
            <span>{layout.widgets.length} widgets</span>
          </span>
          <span className="flex items-center space-x-1">
            <Clock className="w-3 h-3" />
            <span>{layout.updatedAt.toLocaleDateString()}</span>
          </span>
        </div>
        {layout.autoGenerated && (
          <span className="px-2 py-1 bg-purple-100 dark:bg-purple-900/30 text-purple-600 dark:text-purple-400 rounded text-xs">
            AI Generated
          </span>
        )}
      </div>

      {/* Tags */}
      {layout.metadata?.tags && layout.metadata.tags.length > 0 && (
        <div className="flex flex-wrap gap-1 mb-3">
          {layout.metadata.tags.slice(0, 3).map(tag => (
            <span
              key={tag}
              className="px-2 py-1 text-xs bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-400 rounded"
            >
              {tag}
            </span>
          ))}
          {layout.metadata.tags.length > 3 && (
            <span className="px-2 py-1 text-xs bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-400 rounded">
              +{layout.metadata.tags.length - 3}
            </span>
          )}
        </div>
      )}

      {/* Actions */}
      <AnimatePresence>
        {showActions && (
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: 10 }}
            className="absolute inset-x-4 bottom-4 flex items-center justify-between bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg shadow-lg p-2"
            onClick={(e: React.MouseEvent) => e.stopPropagation()}
          >
            <div className="flex items-center space-x-1">
              <button
                onClick={onDuplicate}
                className="p-1 text-gray-600 dark:text-gray-400 hover:text-blue-600 dark:hover:text-blue-400 rounded"
                title="Duplicate"
              >
                <Copy className="w-4 h-4" />
              </button>
              <button
                onClick={onExport}
                className="p-1 text-gray-600 dark:text-gray-400 hover:text-green-600 dark:hover:text-green-400 rounded"
                title="Export"
              >
                <Download className="w-4 h-4" />
              </button>
              <button
                onClick={handleShare}
                disabled={isSharing}
                className="p-1 text-gray-600 dark:text-gray-400 hover:text-purple-600 dark:hover:text-purple-400 rounded disabled:opacity-50"
                title="Share"
              >
                <Share2 className="w-4 h-4" />
              </button>
            </div>
            
            <div className="flex items-center space-x-1">
              {!layout.isDefault && (
                <button
                  onClick={onSetDefault}
                  className="p-1 text-gray-600 dark:text-gray-400 hover:text-yellow-600 dark:hover:text-yellow-400 rounded"
                  title="Set as Default"
                >
                  <StarOff className="w-4 h-4" />
                </button>
              )}
              {canDelete && (
                <button
                  onClick={onDelete}
                  className="p-1 text-gray-600 dark:text-gray-400 hover:text-red-600 dark:hover:text-red-400 rounded"
                  title="Delete"
                >
                  <Trash2 className="w-4 h-4" />
                </button>
              )}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
};

export const LayoutManager: React.FC<LayoutManagerProps> = ({
  layouts,
  currentLayout,
  currentMode,
  onLayoutSelect,
  onLayoutSave,
  onLayoutDelete,
  onLayoutDuplicate,
  onLayoutExport,
  onLayoutImport,
  onLayoutSetDefault,
  onLayoutShare,
  className
}) => {
  const [searchTerm, setSearchTerm] = useState('');
  const [filterBy, setFilterBy] = useState<'all' | 'default' | 'custom' | 'ai-generated'>('all');
  const [showSaveDialog, setShowSaveDialog] = useState(false);
  const [showImportDialog, setShowImportDialog] = useState(false);
  const [saveLayoutName, setSaveLayoutName] = useState('');
  const [saveLayoutDescription, setSaveLayoutDescription] = useState('');
  const [duplicateLayoutId, setDuplicateLayoutId] = useState<string | null>(null);
  const [duplicateLayoutName, setDuplicateLayoutName] = useState('');
  const [isSaving, setIsSaving] = useState(false);

  // Filter and search layouts
  const filteredLayouts = useMemo(() => {
    let filtered = layouts;

    // Filter by type
    switch (filterBy) {
      case 'default':
        filtered = filtered.filter(layout => layout.isDefault);
        break;
      case 'custom':
        filtered = filtered.filter(layout => !layout.isDefault && !layout.autoGenerated);
        break;
      case 'ai-generated':
        filtered = filtered.filter(layout => layout.autoGenerated);
        break;
    }

    // Filter by search term
    if (searchTerm) {
      const term = searchTerm.toLowerCase();
      filtered = filtered.filter(layout =>
        layout.name.toLowerCase().includes(term) ||
        layout.metadata?.description?.toLowerCase().includes(term) ||
        layout.metadata?.tags?.some(tag => tag.toLowerCase().includes(term))
      );
    }

    // Sort by updated date (newest first)
    return filtered.sort((a, b) => b.updatedAt.getTime() - a.updatedAt.getTime());
  }, [layouts, searchTerm, filterBy]);

  // Event handlers
  const handleSaveLayout = useCallback(async () => {
    if (!saveLayoutName.trim()) return;
    
    setIsSaving(true);
    try {
      await onLayoutSave(saveLayoutName.trim(), saveLayoutDescription.trim() || undefined);
      setShowSaveDialog(false);
      setSaveLayoutName('');
      setSaveLayoutDescription('');
    } catch (error) {
      console.error('Failed to save layout:', error);
    } finally {
      setIsSaving(false);
    }
  }, [saveLayoutName, saveLayoutDescription, onLayoutSave]);

  const handleDuplicateLayout = useCallback(async () => {
    if (!duplicateLayoutId || !duplicateLayoutName.trim()) return;
    
    try {
      await onLayoutDuplicate(duplicateLayoutId, duplicateLayoutName.trim());
      setDuplicateLayoutId(null);
      setDuplicateLayoutName('');
    } catch (error) {
      console.error('Failed to duplicate layout:', error);
    }
  }, [duplicateLayoutId, duplicateLayoutName, onLayoutDuplicate]);

  const handleImportLayout = useCallback((event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = async (e) => {
      try {
        const layout = JSON.parse(e.target?.result as string);
        await onLayoutImport(layout);
        setShowImportDialog(false);
      } catch (error) {
        console.error('Failed to import layout:', error);
      }
    };
    reader.readAsText(file);
  }, [onLayoutImport]);

  return (
    <div className={cn("space-y-6", className)}>
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold text-gray-900 dark:text-gray-100">
            Layout Manager
          </h2>
          <p className="text-gray-600 dark:text-gray-400">
            Manage your dashboard layouts for {currentMode === 'c-level' ? 'C-Level' : 'D-Level'} mode
          </p>
        </div>
        <div className="flex items-center space-x-3">
          <button
            onClick={() => setShowSaveDialog(true)}
            className="flex items-center space-x-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
          >
            <Save className="w-4 h-4" />
            <span>Save Current</span>
          </button>
          <button
            onClick={() => setShowImportDialog(true)}
            className="flex items-center space-x-2 px-4 py-2 border border-gray-300 dark:border-gray-600 text-gray-700 dark:text-gray-300 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors"
          >
            <Upload className="w-4 h-4" />
            <span>Import</span>
          </button>
        </div>
      </div>

      {/* Search and Filter */}
      <div className="flex items-center space-x-4">
        <div className="flex-1 relative">
          <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-4 h-4" />
          <input
            type="text"
            placeholder="Search layouts..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full pl-10 pr-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-gray-100 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          />
        </div>
        <select
          value={filterBy}
          onChange={(e) => setFilterBy(e.target.value as any)}
          className="px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-gray-100 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
        >
          <option value="all">All Layouts</option>
          <option value="default">Default</option>
          <option value="custom">Custom</option>
          <option value="ai-generated">AI Generated</option>
        </select>
      </div>

      {/* Layouts Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {filteredLayouts.map(layout => (
          <LayoutCard
            key={layout.id}
            layout={layout}
            isActive={currentLayout?.id === layout.id}
            onSelect={() => onLayoutSelect(layout.id)}
            onDelete={() => onLayoutDelete(layout.id)}
            onDuplicate={() => {
              setDuplicateLayoutId(layout.id);
              setDuplicateLayoutName(`${layout.name} (Copy)`);
            }}
            onExport={() => onLayoutExport(layout.id)}
            onSetDefault={() => onLayoutSetDefault(layout.id)}
            onShare={() => onLayoutShare(layout.id)}
            canDelete={!layout.isDefault}
          />
        ))}
      </div>

      {/* Empty State */}
      {filteredLayouts.length === 0 && (
        <div className="text-center py-12">
          <Layout className="mx-auto h-12 w-12 text-gray-400 mb-4" />
          <h3 className="text-lg font-medium text-gray-900 dark:text-gray-100 mb-2">
            No layouts found
          </h3>
          <p className="text-gray-600 dark:text-gray-400 mb-4">
            {searchTerm || filterBy !== 'all'
              ? "Try adjusting your search or filter criteria"
              : "Create your first custom layout to get started"
            }
          </p>
          {(searchTerm || filterBy !== 'all') && (
            <button
              onClick={() => {
                setSearchTerm('');
                setFilterBy('all');
              }}
              className="px-4 py-2 text-sm bg-blue-600 text-white rounded hover:bg-blue-700 transition-colors"
            >
              Clear Filters
            </button>
          )}
        </div>
      )}

      {/* Save Layout Dialog */}
      <AnimatePresence>
        {showSaveDialog && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50"
          >
            <motion.div
              initial={{ scale: 0.95 }}
              animate={{ scale: 1 }}
              exit={{ scale: 0.95 }}
              className="bg-white dark:bg-gray-800 rounded-lg shadow-xl border border-gray-200 dark:border-gray-700 w-96 p-6"
            >
              <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-4">
                Save Current Layout
              </h3>
              
              <div className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Layout Name *
                  </label>
                  <input
                    type="text"
                    value={saveLayoutName}
                    onChange={(e) => setSaveLayoutName(e.target.value)}
                    placeholder="Enter layout name..."
                    className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-gray-100 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                    autoFocus
                  />
                </div>
                
                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Description (Optional)
                  </label>
                  <textarea
                    value={saveLayoutDescription}
                    onChange={(e) => setSaveLayoutDescription(e.target.value)}
                    placeholder="Describe this layout..."
                    rows={3}
                    className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-gray-100 focus:ring-2 focus:ring-blue-500 focus:border-transparent resize-none"
                  />
                </div>
              </div>

              <div className="flex items-center justify-end space-x-3 mt-6">
                <button
                  onClick={() => {
                    setShowSaveDialog(false);
                    setSaveLayoutName('');
                    setSaveLayoutDescription('');
                  }}
                  className="px-4 py-2 text-sm font-medium text-gray-700 dark:text-gray-300 hover:text-gray-900 dark:hover:text-gray-100 transition-colors"
                >
                  Cancel
                </button>
                <button
                  onClick={handleSaveLayout}
                  disabled={!saveLayoutName.trim() || isSaving}
                  className="px-4 py-2 text-sm font-medium bg-blue-600 text-white rounded hover:bg-blue-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  {isSaving ? 'Saving...' : 'Save Layout'}
                </button>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Duplicate Layout Dialog */}
      <AnimatePresence>
        {duplicateLayoutId && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50"
          >
            <motion.div
              initial={{ scale: 0.95 }}
              animate={{ scale: 1 }}
              exit={{ scale: 0.95 }}
              className="bg-white dark:bg-gray-800 rounded-lg shadow-xl border border-gray-200 dark:border-gray-700 w-96 p-6"
            >
              <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-4">
                Duplicate Layout
              </h3>
              
              <div className="mb-4">
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                  New Layout Name
                </label>
                <input
                  type="text"
                  value={duplicateLayoutName}
                  onChange={(e) => setDuplicateLayoutName(e.target.value)}
                  placeholder="Enter new layout name..."
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-gray-100 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  autoFocus
                />
              </div>

              <div className="flex items-center justify-end space-x-3">
                <button
                  onClick={() => {
                    setDuplicateLayoutId(null);
                    setDuplicateLayoutName('');
                  }}
                  className="px-4 py-2 text-sm font-medium text-gray-700 dark:text-gray-300 hover:text-gray-900 dark:hover:text-gray-100 transition-colors"
                >
                  Cancel
                </button>
                <button
                  onClick={handleDuplicateLayout}
                  disabled={!duplicateLayoutName.trim()}
                  className="px-4 py-2 text-sm font-medium bg-blue-600 text-white rounded hover:bg-blue-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  Duplicate
                </button>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Import Dialog */}
      <AnimatePresence>
        {showImportDialog && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50"
          >
            <motion.div
              initial={{ scale: 0.95 }}
              animate={{ scale: 1 }}
              exit={{ scale: 0.95 }}
              className="bg-white dark:bg-gray-800 rounded-lg shadow-xl border border-gray-200 dark:border-gray-700 w-96 p-6"
            >
              <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-4">
                Import Layout
              </h3>
              
              <div className="mb-4">
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                  Select Layout File
                </label>
                <input
                  type="file"
                  accept=".json"
                  onChange={handleImportLayout}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-gray-100 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
                <p className="mt-2 text-xs text-gray-500 dark:text-gray-400">
                  Select a JSON file exported from another dashboard
                </p>
              </div>

              <div className="flex items-center justify-end space-x-3">
                <button
                  onClick={() => setShowImportDialog(false)}
                  className="px-4 py-2 text-sm font-medium text-gray-700 dark:text-gray-300 hover:text-gray-900 dark:hover:text-gray-100 transition-colors"
                >
                  Cancel
                </button>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};