openapi: 3.0.3
info:
  title: ChurnVision Data Management API
  description: Intuitive data management endpoints for non-technical users
  version: 1.0.0
  contact:
    name: ChurnVision Enterprise
    url: https://churnvision.example.com

servers:
  - url: http://localhost:8000/api/v1
    description: Development server

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: License-validated JWT token

  schemas:
    Employee:
      type: object
      required: [hr_code, full_name, position, structure_name, status]
      properties:
        hr_code:
          type: string
          description: Unique employee identifier within dataset
          example: "EMP001"
        full_name:
          type: string
          minLength: 2
          maxLength: 100
          description: Employee's complete name
          example: "John Smith"
        position:
          type: string
          description: Job title/role
          example: "Senior Software Engineer"
        structure_name:
          type: string
          description: Department/organizational unit
          example: "Engineering"
        status:
          type: string
          enum: [active, inactive, terminated]
          description: Employment status
          example: "active"
        last_modified:
          type: string
          format: date-time
          description: Last modification timestamp
        modified_by:
          type: string
          description: User ID who made last change
        data_quality_score:
          type: number
          minimum: 0.0
          maximum: 1.0
          description: Data completeness score
          example: 0.95

    EmployeeList:
      type: object
      required: [data, total, page, page_size, has_more]
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Employee'
        total:
          type: integer
          minimum: 0
          description: Total number of employees matching criteria
        page:
          type: integer
          minimum: 0
          description: Current page number (0-based)
        page_size:
          type: integer
          minimum: 1
          maximum: 100
          description: Number of items per page
        has_more:
          type: boolean
          description: Whether more pages are available

    DataUpload:
      type: object
      required: [upload_id, filename, file_size, processing_status]
      properties:
        upload_id:
          type: string
          format: uuid
          description: Unique upload identifier
        filename:
          type: string
          description: Original file name
          example: "employee_data.xlsx"
        file_size:
          type: integer
          minimum: 1
          maximum: 52428800
          description: File size in bytes
        file_type:
          type: string
          enum: [
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            "text/csv"
          ]
          description: File MIME type
        upload_timestamp:
          type: string
          format: date-time
          description: Upload initiation time
        processing_status:
          type: string
          enum: [pending, processing, completed, failed]
          description: Current processing status
        validation_results:
          type: object
          description: Detailed validation results and errors
        records_processed:
          type: integer
          minimum: 0
          description: Number of records processed
        records_created:
          type: integer
          minimum: 0
          description: Number of new employees created
        records_updated:
          type: integer
          minimum: 0
          description: Number of existing employees updated
        error_summary:
          type: string
          description: High-level error description

    SearchResult:
      type: object
      required: [employees, total_results, query_time_ms]
      properties:
        employees:
          type: array
          items:
            allOf:
              - $ref: '#/components/schemas/Employee'
              - type: object
                properties:
                  search_rank:
                    type: number
                    description: Search relevance score
                  highlight:
                    type: object
                    description: Highlighted search terms in results
        total_results:
          type: integer
          minimum: 0
          description: Total number of matching employees
        query_time_ms:
          type: integer
          minimum: 0
          description: Query execution time in milliseconds
        filters_applied:
          type: object
          description: Active filters used in search

    EmployeeUpdate:
      type: object
      properties:
        full_name:
          type: string
          minLength: 2
          maxLength: 100
        position:
          type: string
        structure_name:
          type: string
        status:
          type: string
          enum: [active, inactive, terminated]
        change_reason:
          type: string
          description: Optional reason for the change

    DataChange:
      type: object
      required: [change_id, change_timestamp, change_type, field_changes]
      properties:
        change_id:
          type: string
          format: uuid
        change_timestamp:
          type: string
          format: date-time
        change_type:
          type: string
          enum: [create, update, delete, bulk_import]
        field_changes:
          type: object
          description: Before/after values for changed fields
        change_source:
          type: string
          enum: [manual_edit, file_upload, bulk_operation, system]
        change_reason:
          type: string
          description: User-provided reason for change
        changed_by:
          type: string
          description: User ID who made the change

    ErrorResponse:
      type: object
      required: [error, message]
      properties:
        error:
          type: string
          description: Error type identifier
        message:
          type: string
          description: Human-readable error message
        details:
          type: object
          description: Additional error context

security:
  - BearerAuth: []

paths:
  /data-management/employees:
    get:
      tags: [Data Overview]
      summary: Get paginated employee list with filtering
      description: Retrieve employees for data overview and navigation (User Story 1)
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            minimum: 0
            default: 0
          description: Page number (0-based)
        - name: page_size
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 50
          description: Number of items per page
        - name: status
          in: query
          schema:
            type: string
            enum: [active, inactive, terminated]
          description: Filter by employment status
        - name: structure_name
          in: query
          schema:
            type: string
          description: Filter by department/structure
        - name: sort_by
          in: query
          schema:
            type: string
            enum: [full_name, position, structure_name, last_modified]
            default: full_name
          description: Sort field
        - name: sort_order
          in: query
          schema:
            type: string
            enum: [asc, desc]
            default: asc
          description: Sort direction
      responses:
        '200':
          description: Employee list retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeeList'
        '400':
          description: Invalid query parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /data-management/employees/search:
    get:
      tags: [Search]
      summary: Search employees with natural language queries
      description: Find employees using natural language search (User Story 4)
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
            minLength: 1
            maxLength: 500
          description: Search query (natural language or simple text)
          example: "sales team hired this year"
        - name: search_type
          in: query
          schema:
            type: string
            enum: [fulltext, semantic, hybrid]
            default: hybrid
          description: Type of search algorithm to use
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
          description: Maximum number of results
      responses:
        '200':
          description: Search results retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResult'
        '400':
          description: Invalid search query
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /data-management/employees/{hr_code}:
    get:
      tags: [Employee Details]
      summary: Get individual employee details
      description: Retrieve specific employee information for editing
      parameters:
        - name: hr_code
          in: path
          required: true
          schema:
            type: string
          description: Employee HR code
      responses:
        '200':
          description: Employee details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
        '404':
          description: Employee not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    patch:
      tags: [Employee Editing]
      summary: Update employee information
      description: Edit employee data using simple form interface (User Story 3)
      parameters:
        - name: hr_code
          in: path
          required: true
          schema:
            type: string
          description: Employee HR code
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmployeeUpdate'
      responses:
        '200':
          description: Employee updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
        '400':
          description: Validation errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Employee not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /data-management/employees/{hr_code}/history:
    get:
      tags: [Audit Trail]
      summary: Get employee change history
      description: Retrieve audit trail for employee modifications
      parameters:
        - name: hr_code
          in: path
          required: true
          schema:
            type: string
          description: Employee HR code
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
          description: Number of change records to return
      responses:
        '200':
          description: Change history retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  changes:
                    type: array
                    items:
                      $ref: '#/components/schemas/DataChange'

  /data-management/uploads:
    post:
      tags: [File Upload]
      summary: Upload employee data file
      description: Upload Excel or CSV file for data import (User Story 2)
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required: [file]
              properties:
                file:
                  type: string
                  format: binary
                  description: Excel (.xlsx) or CSV (.csv) file
                update_mode:
                  type: string
                  enum: [create_only, update_only, create_and_update]
                  default: create_and_update
                  description: How to handle existing employees
      responses:
        '202':
          description: Upload accepted for processing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataUpload'
        '400':
          description: Invalid file or parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '413':
          description: File too large (max 50MB)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    get:
      tags: [File Upload]
      summary: List upload history
      description: Get history of file uploads for monitoring
      parameters:
        - name: status
          in: query
          schema:
            type: string
            enum: [pending, processing, completed, failed]
          description: Filter by processing status
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 50
            default: 10
          description: Number of upload records to return
      responses:
        '200':
          description: Upload history retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  uploads:
                    type: array
                    items:
                      $ref: '#/components/schemas/DataUpload'

  /data-management/uploads/{upload_id}:
    get:
      tags: [File Upload]
      summary: Get upload status and results
      description: Check progress and results of file upload processing
      parameters:
        - name: upload_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Upload identifier
      responses:
        '200':
          description: Upload details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataUpload'
        '404':
          description: Upload not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /data-management/statistics:
    get:
      tags: [Data Overview]
      summary: Get data overview statistics
      description: Retrieve summary statistics for data overview (User Story 1)
      responses:
        '200':
          description: Statistics retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_employees:
                    type: integer
                    description: Total employee count
                  active_employees:
                    type: integer
                    description: Active employee count
                  data_completeness:
                    type: number
                    minimum: 0.0
                    maximum: 1.0
                    description: Overall data quality score
                  last_update:
                    type: string
                    format: date-time
                    description: Last data modification time
                  departments:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        employee_count:
                          type: integer
                        avg_data_quality:
                          type: number

  /data-management/ws:
    get:
      tags: [Real-time Updates]
      summary: WebSocket connection for real-time updates
      description: Establish WebSocket connection for collaborative editing
      responses:
        '101':
          description: WebSocket connection established
        '403':
          description: Authentication required